module.exports = {
  PORT: process.env.PORT || 5001,
  TOKEN_KEY: process.env.TOKEN_KEY || "MY_SECRET",
  FIREBASE_PROJECT_ID: process.env.FIREBASE_PROJECT_ID,
  FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
  FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
};
